services:
  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    env_file:
      - .env
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      SUMMARY_MODEL: ${SUMMARY_MODEL:-gpt-4.1-mini}
      EMBEDDING_MODEL: ${EMBEDDING_MODEL:-text-embedding-3-large}
    volumes:
      - ./data:/app/data
      - ./pipeline:/app/pipeline
      - ./api:/app/api
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    depends_on:
      - api
    ports:
      - "3000:80"
    restart: unless-stopped
